version: '2.4'

services:
    python:
        image: maresh/hll_rcon:latest
        environment:
            HLL_HOST: ${HLL_HOST}
            HLL_PORT: ${HLL_PORT}
            HLL_PASSWORD: ${HLL_PASSWORD}
            LOGGING_LEVEL: 'INFO'
            LOGGING_PATH: /logs/
            REDIS_URL: redis://redis:6379/0
            DB_URL: 'postgres://rcon:${HLL_DB_PASSWORD}@postgres:5432'
            DISCORD_WEBHOOK_AUDIT_LOG: ${DISCORD_WEBHOOK_AUDIT_LOG}
            RCONWEB_API_SECRET: ${RCONWEB_API_SECRET}
            SERVER_SHORT_NAME: ${SERVER_SHORT_NAME}
            DISCORD_CHAT_WEBHOOK: ${DISCORD_CHAT_WEBHOOK}
            DISCORD_CHAT_WEBHOOK_ALLOW_MENTIONS: ${DISCORD_CHAT_WEBHOOK_ALLOW_MENTIONS}
            DISCORD_PING_TRIGGER_WORDS: ${DISCORD_PING_TRIGGER_WORDS}
            DISCORD_PING_TRIGGER_ROLES: ${DISCORD_PING_TRIGGER_ROLES}
            DISCORD_KILLS_WEBHOOK: ${DISCORD_KILLS_WEBHOOK}
            DISCORD_SEND_KILL_UPDATES: ${DISCORD_SEND_KILL_UPDATES}
            DISCORD_SEND_TEAM_KILL_UPDATES: ${DISCORD_SEND_TEAM_KILL_UPDATES}
        restart: always
        volumes: 
            - ./logs:/logs/
            - ./servicediscovery:/servicediscovery
    